/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Domain.ClienteSingleton;
import Domain.Jugador;
import Domain.Oponente;
import Domain.Solicitud;
import Domain.Usuario;
import Utility.Disenio;
import Utility.GestionXML;
import java.util.ArrayList;
import org.jdom.Element;

/**
 *
 * @author Ernesto
 */
public class JFInterfazUsuario extends javax.swing.JFrame {

    private final ClienteSingleton clienteJuego;
    private final Usuario usuario;
    private JFChatTexto muro;
    private JfEditorMapa editor;
    private JfVentanaDeJuego ventanaPrincipal;
    private JFRanking ranking;
    private JIFIniciarPartida inicarPartida;
    private JfVentanaDeJuego ventanaDeJuego;
    private JIFSolicitudes solicitudesResibidas;

    /**
     * @param usuario
     */
    public JFInterfazUsuario(Usuario usuario) {
        super(usuario.getNombreUsuario());
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.clienteJuego = ClienteSingleton.getInstance();
        this.usuario = usuario;
        this.ranking = new JFRanking();
    }//constructor

    //metodos de acceso
    public Usuario getUsuario() {
        return usuario;
    }

    public JfEditorMapa getEditor() {
        return editor;
    }

    public JfVentanaDeJuego getVentanaPrincipal() {
        return ventanaPrincipal;
    }

    public JFRanking getRanking() {
        return ranking;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(Disenio.COLOR_FONDO);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 204, 153));

        jMenu1.setText("Partidas");

        jMenuItem1.setText("Iniciar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Amigos");

        jMenuItem4.setText("Enviar Solicitud");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem3.setText("Aceptar Solicitud");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Muro");

        jMenuItem5.setText("Publicar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Otros");

        jMenuItem7.setText("Ranking");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuItem8.setText("Salir");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Diseñar Mapa");

        jMenuItem6.setText("Crear");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        ClienteSingleton.getInstance().enviarDatos(GestionXML.xmlToString(GestionXML.crearMensajeProtocolo(Solicitud.RANKING_JUGADORES.name())));
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        Element solicitud = GestionXML.crearMensajeProtocolo(Solicitud.CERRAR_SESSION.name());
        this.clienteJuego.enviarDatos(GestionXML.xmlToString(solicitud));
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        this.muro = new JFChatTexto(this.usuario);
        this.muro.setLocationRelativeTo(this);
        this.muro.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.inicarPartida = new JIFIniciarPartida(this.usuario);
        this.jDesktopPane1.add(this.inicarPartida);
        this.inicarPartida.setVisible(true);
        ClienteSingleton.getInstance().enviarDatos(GestionXML.xmlToString(GestionXML.crearMensajeProtocolo(Solicitud.SOLICITAR_LISTA_AMIGOS.name())));
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        this.editor = new JfEditorMapa(this.usuario);
        this.editor.setLocationRelativeTo(this);
        this.editor.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        JIFEnviarSolicitud jIFEnviarSolicitud = new JIFEnviarSolicitud(this.usuario);
        this.jDesktopPane1.add(jIFEnviarSolicitud);
        jIFEnviarSolicitud.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.solicitudesResibidas = new JIFSolicitudes();
        this.jDesktopPane1.add(this.solicitudesResibidas);
        this.solicitudesResibidas.setVisible(true);
        ClienteSingleton.getInstance().enviarDatos(GestionXML.xmlToString(GestionXML.crearMensajeProtocolo(Solicitud.SOLICITAR_SOLICITUDES.name())));
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    public void abrirAreaDeJuego() {
        if (this.ventanaDeJuego == null) {
            this.ventanaDeJuego = new JfVentanaDeJuego();
            this.ventanaDeJuego.setVisible(true);
            ClienteSingleton.getInstance().enviarDatos(GestionXML.xmlToString(GestionXML.crearMensajeProtocolo(Solicitud.SOLICITAR_OPONENTES.name())));
        }//valida que solo se desplegue una ventana de juego a la vez
    } //habre una nueva ventana de juego

    public void cargarSolicitudes(String[] solicitudes) {
        if (this.solicitudesResibidas != null) {
            this.solicitudesResibidas.cargarSolicitudes(solicitudes);
        }
    }//carga las solicitudes de amistad guardadas del usuario

    public void desplegarJugadorPerdio() {
        this.ventanaDeJuego.dispose();
        this.ventanaDeJuego=null;
        JIFJugadorPerdio jIFJugadorPerdio = new JIFJugadorPerdio();
        this.jDesktopPane1.add(jIFJugadorPerdio);
        jIFJugadorPerdio.setVisible(true);
    }//cierra la ventana de juego y despliega un mensaje de jugador perdio

    public void desplegarJugadorGano(Jugador jugador,ArrayList<Oponente> oponentes) {
        this.ventanaDeJuego.dispose();
        this.ventanaDeJuego=null;
        JIFJugadorGano jIFJugadorGano = new JIFJugadorGano(jugador, oponentes);
        this.jDesktopPane1.add(jIFJugadorGano);
        jIFJugadorGano.setVisible(true);
    }//abre la ventana de victoria

    public void desplagarRanking(String[] usuariosRanking) {
        this.ranking = new JFRanking();
        this.ranking.cargarRanking(usuariosRanking);
        this.ranking.setLocationRelativeTo(this);
        this.ranking.setVisible(true);
    }//desplaga el ranking de juago

    public void cargarAmigos(String[] amigos, String[] mapas) {
        if (this.inicarPartida != null) {
            this.inicarPartida.cargarInfoAmigos(amigos);
            this.inicarPartida.cargarInfoMapas(mapas);
        }
    }//carga la lista de amigos de unjugador

    public void agregarMuro(String publicacion) {
        if (this.muro != null) {
            this.muro.agregarMensaje(publicacion);
        }
    }//llama a la ventana del muro para eagregar una publicaion

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFInterfazUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFInterfazUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFInterfazUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFInterfazUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    // End of variables declaration//GEN-END:variables
}
