/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Domain.Arbol;
import Domain.CasillaAgua;
import Domain.CasillaCamino;
import Domain.CasillaCesped;
import Domain.CasillaMuro;
import Domain.ClienteSingleton;
import Domain.Flor;
import Domain.Punto2D;
import Domain.Roca;
import Domain.Solicitud;
import Domain.Usuario;
import Utility.Disenio;
import Utility.GestionXML;
import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.JOptionPane;
import org.jdom.Element;

/**
 *
 * @author Laboratorios
 */
public class JPanelEditor extends javax.swing.JPanel {

    private final Usuario usuario;
    private CasillaAgua casillaAgua;
    private CasillaCesped casillaCesped;
    private CasillaCamino casillaCamino;
    private CasillaMuro casillaMuro;
    private Flor flor;
    private Arbol arbol;
    private Roca roca;
    private int tipoCasilla;
    private String tipoDecorativo;
    private JPanelVisualizacion visualizacionMapa;

    /**
     * Creates new form JPanellMapa
     * @param usuario
     */
    public JPanelEditor(Usuario usuario) {
        initComponents();
        this.setPreferredSize(new Dimension(880, 840));
        this.usuario=usuario;
        this.init2();
    }

    private void init2() {
        
        this.setFocusable(true);
        this.requestFocus();
        
        this.tipoCasilla=-1;
        this.tipoDecorativo="";
        
        this.casillaAgua = new CasillaAgua(new Punto2D(310, 30));
        this.casillaCesped = new CasillaCesped(new Punto2D(380, 30));
        this.casillaCamino = new CasillaCamino(new Punto2D(450, 30));
        this.casillaMuro = new CasillaMuro(new Punto2D(520, 30));
        this.flor=new Flor(new Punto2D(340, 100));
        this.roca=new Roca(new Punto2D(420, 100));
        this.arbol=new Arbol(new Punto2D(490, 100));

        this.visualizacionMapa = new JPanelVisualizacion(this);
        this.add(this.visualizacionMapa);
        this.visualizacionMapa.setBounds(40, 190, 800, 600);

    }//carga de componentes
    
    //metodos de colicion

    public int getTipoCasilla() {
        return tipoCasilla;
    }

    public String getTipoDecorativo() {
        return tipoDecorativo;
    }


    @Override
    public void paintComponent(Graphics g) {

        g.setColor(Disenio.COLOR_FONDO);
        g.fillRect(0, 0, this.getPreferredSize().width, this.getPreferredSize().height);
        this.casillaAgua.dibujar(g);
        this.casillaCesped.dibujar(g);
        this.casillaCamino.dibujar(g);
        this.casillaMuro.dibujar(g);
        this.arbol.dibujar(g);
        this.roca.dibujar(g);
        this.flor.dibujar(g);

    }//metodo de dibujado

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jftfAlto = new javax.swing.JFormattedTextField();
        jftfAncho = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtfNombreMapa = new javax.swing.JTextField();

        setBackground(Disenio.COLOR_FONDO);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jftfAlto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jftfAncho.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel1.setText("Ancho");

        jLabel2.setText("Alto");

        jButton1.setText("Establecer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Crear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Casilla");

        jLabel4.setText("Decorativos");

        jButton3.setText("Abajo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Arriba");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Derecha");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Izquierda");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel5.setText("Nombre Mapa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jftfAncho, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(jftfAlto)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jButton1)))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(72, 72, 72))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jtfNombreMapa, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addGap(305, 305, 305)
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 293, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jftfAncho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jftfAlto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel5)
                        .addGap(15, 15, 15)
                        .addComponent(jtfNombreMapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4)))
                .addGap(39, 39, 39)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 612, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton3)
                    .addComponent(jButton6))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int alto=Integer.parseInt(this.jftfAlto.getText());
        int ancho=Integer.parseInt(this.jftfAncho.getText());
        if (alto >= 600  && ancho >= 800) {
            this.visualizacionMapa.cargarMapa(ancho, alto);
        } else {
            JOptionPane.showMessageDialog(this, "Dimenciones invalidas");
        }//carga el mapa en el scroll
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       this.visualizacionMapa.getMapaNuevo().vertical(1);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      this.visualizacionMapa.getMapaNuevo().vertical(-1);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      this.visualizacionMapa.getMapaNuevo().horizontal(1);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       this.visualizacionMapa.getMapaNuevo().horizontal(-1);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

        if (this.casillaAgua.esSeleccionada(new Punto2D(evt.getX(), evt.getY()))) {
            this.tipoCasilla = this.casillaAgua.retornarTipo();
        }

        if (this.casillaCesped.esSeleccionada(new Punto2D(evt.getX(), evt.getY()))) {
            this.tipoCasilla = this.casillaCesped.retornarTipo();
        }

        if (this.casillaCamino.esSeleccionada(new Punto2D(evt.getX(), evt.getY()))) {
            this.tipoCasilla = this.casillaCamino.retornarTipo();
        }

        if (this.casillaMuro.esSeleccionada(new Punto2D(evt.getX(), evt.getY()))) {
            this.tipoCasilla = this.casillaMuro.retornarTipo();
        }

        if (this.arbol.seleccionado(new Punto2D(evt.getX(), evt.getY()))) {
            this.soloObjetos();
            this.tipoDecorativo = this.arbol.retornarTipo();
        }

        if (this.roca.seleccionado(new Punto2D(evt.getX(), evt.getY()))) {
            this.soloObjetos();
            this.tipoDecorativo = this.roca.retornarTipo();
        }

        if (this.flor.seleccionado(new Punto2D(evt.getX(), evt.getY()))) {
            this.soloObjetos();
            this.tipoDecorativo = this.flor.retornarTipo();
        }
    }//GEN-LAST:event_formMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       Element mapaEnviar=GestionXML.empaquetarMapa(this.usuario.getNombreUsuario()
               ,this.jtfNombreMapa.getText(), this.visualizacionMapa.getMapaNuevo());
       
        ClienteSingleton.getInstance().enviarDatos(GestionXML.xmlToString(GestionXML.enviarMapa(Solicitud.GUARDAR_MAPA.name(), mapaEnviar)));
        this.visualizacionMapa.setMapaNuevo(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    public void soloObjetos() {
        this.tipoCasilla = -1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JFormattedTextField jftfAlto;
    private javax.swing.JFormattedTextField jftfAncho;
    private javax.swing.JTextField jtfNombreMapa;
    // End of variables declaration//GEN-END:variables
}
