package GUI;

import Domain.Mapa;
import Domain.Punto2D;
import Utility.Disenio;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author Ernesto
 */
public class JPanelVisualizacion extends javax.swing.JPanel {

    private final JPanelEditor panelPadre;
    private Mapa mapaNuevo;

    /**
     * Creates new form JPVisualizacionMapa
     *
     * @param panelPadre
     */
    public JPanelVisualizacion(JPanelEditor panelPadre) {
        initComponents();
        this.panelPadre=panelPadre;
        this.setPreferredSize(new Dimension(800, 600));
        this.setFocusable(true);
        this.requestFocus();
    }//constructor

    public void cargarMapa(int ancho, int alto) {
        this.setPreferredSize(new Dimension(ancho, alto));
        this.mapaNuevo = new Mapa(alto / Disenio.CASILLA, ancho / Disenio.CASILLA);
        this.mapaNuevo.cargarPorDefecto();
    }//metodo para generar un mapa nuevo

    public Mapa getMapaNuevo() {
        return mapaNuevo;
    }

    public void setMapaNuevo(Mapa mapaNuevo) {
        this.mapaNuevo = mapaNuevo;
    }
    
    @Override
    public void paintComponent(Graphics g) {
        g.setColor(Color.BLACK);
        g.fillRect(0, 0, 800, 600);
        if (this.mapaNuevo!=null) {
         this.mapaNuevo.dibujar(g);   
        }//verifica si hay un mapa para editar
        repaint();
    }//metodo de dibujado
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

        if (this.panelPadre.getTipoCasilla() != -1) {
            this.mapaNuevo.colocarCasilla(this.panelPadre.getTipoCasilla(), new Punto2D(evt.getX(), evt.getY()));
        } else {
            this.mapaNuevo.colocarDecoracion(this.panelPadre.getTipoDecorativo(), this.mapaNuevo.obtenerCasilla(new Punto2D(evt.getX(), evt.getY())));
        }
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
